services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  allejo\stakx\AssetEngine\:
    resource: '../../AssetEngine/*'

  allejo\stakx\AssetEngine\AssetEngineManager:
    calls:
      - method: addAssetEngines
        arguments: [!tagged stakx.asset_engine]

  allejo\stakx\Compilation\:
    resource: '../../Compilation/*'

  allejo\stakx\DataTransformer\:
    resource: '../../DataTransformer/*'

  allejo\stakx\DataTransformer\DataTransformerManager:
    calls:
      - method: addDataTransformers
        arguments: [!tagged stakx.data_transformer]

  allejo\stakx\MarkupEngine\:
    resource: '../../MarkupEngine/*'

  allejo\stakx\MarkupEngine\MarkupEngineManager:
    calls:
      - method: addMarkupEngines
        arguments: [!tagged stakx.markup_engine]

  allejo\stakx\Manager\:
    resource: '../../Manager/*'
    calls:
      - { method: 'compileManager', arguments: [] }

  allejo\stakx\Manager\ThemeManager:
    arguments:
      - null

  allejo\stakx\EventSubscriber\:
    resource: '../../EventSubscriber/*'
    tags:
      - { name: 'kernel.event_subscriber' }

  allejo\stakx\Server\:
    resource: '../../Server/*'

  allejo\stakx\Templating\Twig\Extension\:
    resource: '../../Templating/Twig/Extension/*'

  allejo\stakx\Templating\Twig\TwigExtension:
    calls:
      - method: addFilters
        arguments: [!tagged stakx.twig_filter]
      - method: addFunctions
        arguments: [!tagged stakx.twig_function]

  allejo\stakx\Templating\TemplateBridgeInterface:
    class: allejo\stakx\Templating\Twig\TwigStakxBridge
    factory: ['allejo\stakx\Templating\Twig\TwigStakxBridgeFactory', createTwigEnvironment]

  Psr\Log\LoggerInterface:
    class: allejo\stakx\Logger
    arguments:
      - '@output'

  Symfony\Contracts\EventDispatcher\EventDispatcherInterface:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  output:
    class: Symfony\Component\Console\Output\ConsoleOutput
